font_size 14.0

map ctrl+v paste_from_clipboard
map ctrl+c copy_and_clear_or_interrupt
mouse_map right press ungrabbed no_op
mouse_map right click ungrabbed paste_from_clipboard
mouse_map right press ungrabbed no_op
mouse_map right click ungrabbed paste_from_clipboard
